### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Dumeowmeow** [buaacyw/MeshAnythingV2#13]
Thank you for your great work!
I observed that the generated mesh has no color, how do I color it correctly according to the original color?

**Comment by buaacyw** [comment]
Hi! Thanks for your interest!
I don't think simply apply the origin texture to the new mesh will work.
The origin texture needs to be modified and thus this should be a future work.

**Comment by Dumeowmeow** [comment]
Thank you for your reply!I have another question,does the generated mesh contain illumination information?

**Comment by buaacyw** [comment]
Thanks! They Don't contain.
