### ISSUE TITLE
no as good as meshanythingV1?

### ISSUE THREAD

**Issue by runshengdu** [buaacyw/MeshAnythingV2#5]
Hello, I am conducting some tests on MeshAnythingV2, but the resulting mesh is unsatisfactory.
![微信图片_20240807144423](https://github.com/user-attachments/assets/dcccf5ba-6341-4144-b236-3552b05f8af7)

**Comment by Zeina-T** [comment]
Hi, 
Sorry to bother you but can I know if the original models are generated through some AI mode? if so, do you mind sharing which one it is? They look really good. 
Thanks for the help

**Comment by runshengdu** [comment]
> Hi, Sorry to bother you but can I know if the original models are generated through some AI mode? if so, do you mind sharing which one it is? They look really good. Thanks for the help

yes, these models were generated by ai. (https://hyperhuman.deemos.com/rodin)

**Comment by buaacyw** [comment]
Wow. That's interesting. Why there is not any output for V2?
Could you please share me your input? I will try to figure it our.

**Comment by runshengdu** [comment]
> Wow. That's interesting. Why there is not any output for V2? Could you please share me your input? I will try to figure it our.

the second row is v1, the third row is v2, input models were generated by Rodin. i just sent the input models to you via email.
![untitled](https://github.com/user-attachments/assets/2e011222-f0a2-49ae-a27d-58d8b54dbf42)

**Comment by buaacyw** [comment]
Thanks a lot for your contribution!

**Comment by buaacyw** [comment]
I process it with Marching Cube first (by adding --mc). This makes the input point cloud similar to our training input.
The axe still failed.
This is interesting. I'm trying to find the reason for this.
  
![image](https://github.com/user-attachments/assets/d687a8ff-98a4-4cd4-bbbd-b1cdee489b21)
![image](https://github.com/user-attachments/assets/a30ae015-2856-4ac6-93e1-3a1d18fcb033)
![image](https://github.com/user-attachments/assets/459aa71c-8ffb-4af4-8f0c-9447f946dd64)
![image](https://github.com/user-attachments/assets/7e18f765-3c4c-4cad-8dd1-4767e719b5ae)

**Comment by buaacyw** [comment]
> > Wow. That's interesting. Why there is not any output for V2? Could you please share me your input? I will try to figure it our.
> 
> the second row is v1, the third row is v2, input models were generated by Rodin. i just sent the input models to you via email. ![untitled](https://private-user-images.githubusercontent.com/74289491/355857195-2e011222-f0a2-49ae-a27d-58d8b54dbf42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODE2NzAsIm5iZiI6MTcyMzA4MTM3MCwicGF0aCI6Ii83NDI4OTQ5MS8zNTU4NTcxOTUtMmUwMTEyMjItZjBhMi00OWFlLWEyN2QtNThkOGI1NGRiZjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAxNDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMmEzMGM3NGZjMmI5NjkyNGYwOThkNTBhZmViNWUyYmViZmJkMjQ4MmNmZmNiYzBmMjM2ZDA5MGZkMDFiZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Po3XanKTzPWImjYYDq444QvHf3SXQ48qBBHWhH46bQ)

I think this is because Rodin remeshed its result. There is a domain gap between the sampled point cloud on the remeshed mesh and our training data (point cloud sampled from Maching Cube result). After preprocess with Marching Cube, the result is expected (Sad for the axe failure case).

**Comment by buaacyw** [comment]
I change the Marching Cube resolution from 128 to 256 by adding --mc_level 8.
My cmd: python main.py --input_dir rodin --out_dir mesh_output --input_type mesh --batchsize_per_gpu 8 --mc --mc_level 8

Here is the result. Looks much better:
![image](https://github.com/user-attachments/assets/48ad119e-880d-4ce5-af5b-231615c6bc01)
![image](https://github.com/user-attachments/assets/c48dfaab-4f0c-4c2a-8940-f05728ca43d6)
![image](https://github.com/user-attachments/assets/b6e6ec4a-2a06-4072-aa2c-7379ed2ac2cc)
![image](https://github.com/user-attachments/assets/7dd5a33b-7a68-486c-832e-76c8447eb190)

**Comment by runshengdu** [comment]
Thanks Yiwen Chen, i do the test again, the result is much better than before. But i think the overall topology is not as good as v1:( , face count is too high for some flat surface.
![微信截图_20240809104343](https://github.com/user-attachments/assets/f8daa935-2857-4735-8234-32707e9f1a47)

**Comment by buaacyw** [comment]
> Thanks Yiwen Chen, i do the test again, the result is much better than before. But i think the overall topology is not as good as v1:( , face count is too high for some flat surface. ![微信截图_20240809104343](https://private-user-images.githubusercontent.com/74289491/356442933-f8daa935-2857-4735-8234-32707e9f1a47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDk3NDAsIm5iZiI6MTcyMzI0OTQ0MCwicGF0aCI6Ii83NDI4OTQ5MS8zNTY0NDI5MzMtZjhkYWE5MzUtMjg1Ny00NzM1LTgyMzQtMzI3MDdlOWYxYTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDAwMjQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYmY2YmUxYjRiNzRlMzRmMzcxZDlmMTRkODc0MmNkYTY3M2Y2N2FmMWMwMGEzNjUyNzkwMTcwZDM3OGNkNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8NEoU5e08fuwqcIliYAEhDdAWocr3o7HseuhNjsgH-c)

I'd have to disagree with the idea that 'the face count is too high for some flat surfaces.' For example, in the case of the knife, it's actually a complex curved surface. V1's simpler topology is due to its limited ability to represent shapes accurately, so it simplifies them to the extent it can manage. On the other hand, V2 is much more precise, so it naturally requires a more complex topology.
