### ISSUE TITLE
Question about Rotation Augmentation

### ISSUE THREAD

**Issue by qixuema** [buaacyw/MeshAnythingV2#8]
Hi, Yiwen

Thank you for the incredible work on MeshAnything V2. I have a quick question regarding the rotation augmentation technique used:

- Around which axes (X, Y, Z) are the rotations performed?
- Are the rotations random or within a specific angle range?

Any insights would be greatly appreciated.

**Comment by buaacyw** [comment]
Thanks! We only rotate around Y axis. The rotate angle is uniformly sampled from 0 - 360.

**Comment by qixuema** [comment]
Thank you for the prompt response and clarification.
